api_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: APIBundle:Default:index }

copy:
    pattern: /service/1/op/copy
    defaults: { _controller: APIBundle:Operations:copy }
    requirements:
        _method: POST

rename:
    pattern: /service/1/op/rename
    defaults: { _controller: APIBundle:Operations:rename }
    requirements:
        _method: POST

move:
    pattern: /service/1/op/move
    defaults: { _controller: APIBundle:Operations:move }
    requirements:
        _method: POST

delete:
    pattern: /service/1/op/delete
    defaults: { _controller: APIBundle:Operations:delete }
    requirements:
        _method: POST

list:
    pattern: /service/1/op/list
    defaults: { _controller: APIBundle:Operations:listFiles, folderId: '' }
    requirements:
        _method: POST
