api_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: APIBundle:Default:index }

_rename:
    pattern: /Rename
    defaults: { _controller: APIBundle:File:Rename }

_rename:
    pattern:  /document/{id}
    defaults: { _controller: APIBundle:File:Rename, _format: ~ }
    requirements:
        _method: PUT