# src/Acsilserver/APIBundle/Resources/config/validation.yml
AcsilServer\APIBundle\Entity\Copy:
    properties:
        fromId:
            - NotBlank: ~
            - GreaterThan:
                value: 0
        toPath:
            - NotBlank: ~
            
AcsilServer\APIBundle\Entity\Rename:
    properties:
        fromId:
            - NotBlank: ~
            - GreaterThan:
                value: 0
        toName:
            - NotBlank: ~

AcsilServer\APIBundle\Entity\Delete:
    properties:
        deleteId:
            - NotBlank: ~
            - GreaterThan:
                value: 0