# src/Acsilserver/APIBundle/Resources/config/validation.yml
AcsilServer\APIBundle\Entity\Copy:
    properties:
        fromId:
            - NotBlank: ~
            - GreaterThan:
                value: 0
        toPath:
            - NotBlank: ~
