api:
    #type: rest
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

acsil_server_app:
    resource: "@AcsilServerAppBundle/Resources/config/routing.yml"
    prefix:   /

