#####################################################################################
#                                       Access                                      #
#####################################################################################

_register:
    pattern:  /register/{registerAdmin}
    defaults: { _controller: AcsilServerAppBundle:Security:register, registerAdmin:'' }

_login:
    pattern:  /login/
    defaults: { _controller: AcsilServerAppBundle:Security:login }

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_request:
    pattern:  /request/
    defaults: { _controller: AcsilServerAppBundle:Security:request }


#####################################################################################
#                                        Home                                       #
#####################################################################################

_home:
    pattern:  /
    defaults: { _controller: AcsilServerAppBundle:Default:index }

_acsil:
    pattern:  /acsil/
    defaults: { _controller: AcsilServerAppBundle:Acsil:index }

#####################################################################################
#                                     User admin                                    #
#####################################################################################

_acsiladmins:
    pattern:  /acsil/admins/
    defaults: { _controller: AcsilServerAppBundle:Acsil:admins }

_deleteaccount:
    pattern:  /acsil/admin/delete/{id}
    defaults: { _controller: AcsilServerAppBundle:Security:delete }
    options:
        expose: true

_changerole:
    pattern:  /acsil/admin/changeUserRole/{id}/{role}
    defaults: { _controller: AcsilServerAppBundle:Security:changeRole }
    
#####################################################################################
#                                 File management                                   #
#####################################################################################

_upload:
    pattern:  /acsil/upload/{folderId}
    defaults: { _controller: AcsilServerAppBundle:Upload:upload, folderId: 0 }

_managefile:
    pattern:  /acsil/myfile/{folderId}
    defaults: { _controller: AcsilServerAppBundle:Upload:manage, folderId: 0 }

_sharefile:
    pattern:  /acsil/sharefile/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:share, id:'' }
    options:
        expose: true

_updateuserrights:
    pattern:  /acsil/updateUserRights/{fileId}/{userId}/{newRights}
    defaults: { _controller: AcsilServerAppBundle:Upload:updateRights }
    options:
        expose: true

_deletefile:
    pattern:  /acsil/myfile/delete/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:delete, id: '' }
    options:
        expose: true

_renamefile:
    pattern:  /acsil/myfile/rename/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:rename, id: '' }
    options:
        expose: true

_upload_picture:
    pattern:  /acsil/acount-picture/
    defaults: { _controller: AcsilServerAppBundle:Upload:picture }

_download:
    pattern:  /acsil/download/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:download, id: '' }

_movefile:
    pattern:  /acsil/myfile/move/{id}/{action}
    defaults: { _controller: AcsilServerAppBundle:Upload:move, id: '' }

_pastefile:
    pattern:  /acsil/myfile/paste/{folderId}/
    defaults: { _controller: AcsilServerAppBundle:Upload:paste, folderId: '' }
#####################################################################################
#                               Folder management                                   #
#####################################################################################

_folder:
    pattern:  /acsil/folder/{folderId}
    defaults: { _controller: AcsilServerAppBundle:Upload:folder, folderId: 0 }

_download_folder:
    pattern:  /acsil/folder/download/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:downloadFolder, id: '' }

_delete_folder:
    pattern:  /acsil/folder/delete/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:deleteFolder, id: '' }
