_home:
    pattern:  /
    defaults: { _controller: AcsilServerAppBundle:Default:index }

_register:
    pattern:  /register/
    defaults: { _controller: AcsilServerAppBundle:Security:register }

_login:
    pattern:  /login/
    defaults: { _controller: AcsilServerAppBundle:Security:login }

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_request:
    pattern:  /request/
    defaults: { _controller: AcsilServerAppBundle:Security:request }

_acsil:
    pattern:  /acsil/
    defaults: { _controller: AcsilServerAppBundle:Acsil:index }

_acsiladmins:
    pattern:  /acsil/admins/
    defaults: { _controller: AcsilServerAppBundle:Acsil:admins }

_deleteaccount:
    pattern:  /acsil/admin/delete/{id}
    defaults: { _controller: AcsilServerAppBundle:Security:delete, id: '' }
    
_upload:
    pattern:  /acsil/upload
    defaults: { _controller: AcsilServerAppBundle:Upload:upload }

_managefile:
    pattern:  /acsil/myfile
    defaults: { _controller: AcsilServerAppBundle:Upload:manage }

_deletefile:
    pattern:  /acsil/myfile/delete/{id}
    defaults: { _controller: AcsilServerAppBundle:Upload:delete, id: '' }

_manage_access:
    pattern:  /acsil/myfile/access/{id}/{friendName}
    defaults: { _controller: AcsilServerAppBundle:Upload:manageaccess, id: '', friendName: '' }

_upload_picture:
    pattern:  /acsil/acount-picture
    defaults: { _controller: AcsilServerAppBundle:Upload:picture }