api_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: APIBundle:Default:index }

copy:
    pattern: /service/1/op/copy
    defaults: { _controller: APIBundle:Operations:copy }
    requirements:
        _method: POST

rename:
    pattern: /service/1/op/rename
    defaults: { _controller: APIBundle:Operations:rename }
    requirements:
        _method: POST

move:
    pattern: /service/1/op/move
    defaults: { _controller: APIBundle:Operations:move }
    requirements:
        _method: POST

delete:
    pattern: /service/1/op/delete
    defaults: { _controller: APIBundle:Operations:delete }
    requirements:
        _method: POST

list:
    pattern: /service/1/op/list/{folderId}
    defaults: { _controller: APIBundle:Operations:listFiles, folderId: 0 }
    requirements:
        _method: POST

upload:
    pattern: /service/1/op/upload
    defaults: { _controller: APIBundle:Operations:upload, folderId: '' }
    requirements:
        _method: POST

download:
    pattern: /service/1/op/download/{id}
    defaults: { _controller: APIBundle:Operations:download, id: 0 }
    requirements:
        _method: POST

folder:
    pattern: /service/1/op/folder
    defaults: { _controller: APIBundle:Operations:folder, folderId: '' }
    requirements:
        _method: POST

share:
    pattern: /service/1/op/share/{id}
    defaults: { _controller: APIBundle:Operations:share, id: 0 }
    requirements:
        _method: POST