parameters:
    platform.entity.user.class: Acsilserver\AppBundle\Entity\User
    platform.user.provider.class: Acsilserver\APIBundle\Provider\UserProvider

services:
#    api.example:
#        class: %api.example.class%
#        arguments: [@service_id, "plain_value",
    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory-service: doctrine
        factory-method: getManagerForClass
        arguments: [%platform.entity.user.class%]

    platform.user.repository:
        class: AcsilServer\AppBundle\Entity\UserRepository
        factory-service: platform.user.manager
        factory-method: getRespository
        arguments: [%platform.entity.user.class%]

    platform.user.provider:
        class: %platform.user.provider.class%
        arguments: [%platform.entity.user.class%]
