parameters:
    platform.entity.user.class: AcsilServer\AppBundle\Entity\User
    platform.user.provider.class: AcsilServer\APIBundle\Provider\UserProvider

services:
#    api.example:
#        class: %api.example.class%
#        arguments: [@service_id, "plain_value"]

    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: 
            - "%platform.entity.user.class%"

    platform.user.repository:
        class: AcsilServer\AppBundle\Entity\UserRepository
        factory_service: platform.user.manager
        factory_method: getRespository
        arguments: 
            - "%platform.entity.user.class%"

    platform.user.provider:
        class: "%platform.user.provider.class%"
        arguments: 
            - "@platform.user.repository"
