api:
    #type: rest
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

acsil_server_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: APIBundle:Security:login }

acsil_server_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: APIBundle:Security:loginCheck }

acsil_server_app:
    resource: "@AcsilServerAppBundle/Resources/config/routing.yml"
    prefix:   /
